services:
  - type: web
    name: vectorizer-tool
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
